services:
  - type: web
    name: cvflix-backend
    runtime: docker
    region: frankfurt
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: LOG_LEVEL
        value: INFO
      - key: RENDER
        value: true
      - key: WEB_CONCURRENCY
        value: 1